# Generated by Django 2.2.1 on 2019-07-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='num',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='输入数字')),
                ('imgage', models.ImageField(upload_to='images')),
            ],
        ),
    ]
